### PR TITLE
Ability to configure timeouts on all client requests

### PR DESCRIPTION
**Pull request by kvigen**
This change adds support for adding a timeout to all client requests. It is configurable in the same way that retries are configurable: both on the entire client or a particular request basis.

This seems like a generally useful thing and for now has a very simple interface.

### CODE REVIEW

**Comment by kvigen** [comment]
cc @Christopher-Bradshaw since you were asking about this

**Comment by rgarcia** [comment]
lgtm. Initially I was thinking the `context.Context` interface was good enough for this, but I see value in setting it once when creating a client.

**Comment by Christopher-Bradshaw** [comment]
Very cool, thanks kv 👍

**Comment by kvigen** [comment]
I also was thinking the `context.Context` interface was good enough until I got asked some questions about it.

**Pull request merged**
