### PR TITLE
Bump VERSION by a patch

### PR DESCRIPTION
**Pull request by mcab**
- [X] Run `make build`
- [X] Run `make generate`
- [X] Update the current version in the `/VERSION` file.

Wasn't expecting `go-bindata` to do this, but, it happened.

### CODE REVIEW

**Review by taylor-sutton — APPROVED** [review]

**Review by ghirsch1 — APPROVED** [review]
if you don't care about this dependency I think fine not to add it (maybe I'm misunderstanding)

but seems fine 👍

**Comment by mcab** [comment]
> if you don't care about this dependency I think fine not to add it (maybe I'm misunderstanding)
> 
> but seems fine 👍

Just ran `make build`, `make generate`, and it appeared.

I have no idea why it appeared, which is frustrating. :(

**Comment by ghirsch1** [comment]
looks like it's pulling in github.com/tmthrgd/go-bindata instead of github.com/kevinburke/go-bindata 🤷

**Comment by mcab** [comment]
From private convos, I had an older version of `go-bindata` referenced in my path. 🤦

I can at least make a patch to remove the older dependency, and make it explicitly reference `./bin/go-bindata`. :loading:

**Pull request merged**
