### PR TITLE
Example of using additional properties

### PR DESCRIPTION
**Pull request by kvigen**
Thought it made sense to have at least one example of this in our sample generated code.

### CODE REVIEW

**Comment by cozmo** [comment]
Hmm that's different that how I thought additionalProperties works. LGTM I think?

**Comment by kvigen** [comment]
Out of curiosity, how did you expect them to work?

**Comment by cozmo** [comment]
I've always thought `additionalProperties` was just a boolean, but I read up on it and seems like this is a thing you can do too.

**Comment by kvigen** [comment]
Ah, yeah. That makes sense for raw json schema. For us, I think the common use case will be this - defining a map[string] type.

**Pull request merged**
