### PR TITLE
Changed the default expose name to 'default' instead of 'http'

### PR DESCRIPTION
**Pull request by xavi-**
Related: https://github.com/Clever/template-wag/pull/6

### CODE REVIEW

**Comment by kvigen** [comment]
is there any way we could gradually convert old services to default. Would something like

```
- name: http
  port: 80
  bind: 80
  health_check:
    type: http
    path: /health
- name: default
  port: 80
  bind: 80
  health_check:
    type: http
    path: /health
```

work?

**Comment by xavi-** [comment]
Which services have been moved to wag?

**Comment by kvigen** [comment]
production services currently on Wag: il-token-service, matchmaker-service, badge-generator-service, timeline, and (soon) resolve-ip.

i'm also hoping to be able to migrate existing http services over to it without having to create a new repo / launch.yml / etc..

**Comment by xavi-** [comment]
There a couple of way to maintain reverse compatibility:

- Temporarily hardcode discovery-style env-vars in the upstream dependencies of the apps you listed
- Use some kind of catapult hack / workaround
- Add fallback logic to wag clients. ex:

```golang
url, err := discovery.URL("%s", "default")
if err != nil {
	url, err := discovery.URL("%s", "http")
	if err != nil {
		return err
	}
}
```

To me adding a callback to wag seems the least risky.  I could add it as part of this PR.  It should be temporary.

**Comment by kvigen** [comment]
I like the fallback

**Comment by xavi-** [comment]
Added fallback

**Comment by kvigen** [comment]
lgtm!

you'll be happy to hear that i'm converting this code to Go templates: https://github.com/Clever/wag/pull/68/files. I'll deal with the merge conflicts

**Comment by xavi-** [comment]
Sweet.  Thanks!

**Pull request merged**
