### PR TITLE
Update README.md javascript client section

### PR DESCRIPTION
**Pull request by brollin**
Just some minor readme updates.

### CODE REVIEW

**Comment by kvigen** [comment]
FYI, fixed the build issue here: https://github.com/Clever/wag/pull/158

**Comment by brollin** [comment]
@kvigen sounds good! I'll merge now.

**Comment by samfishman** [comment]
Does the `@clever/` change actually make sense? Other people can use wag too. Not that it's that important.

**Comment by kvigen** [comment]
Good question. Probably worth revisiting once we push this more publicly.

**Pull request merged**
