### PR TITLE
Improve parameter missing error messages

### PR DESCRIPTION
**Pull request by nathanleiby**
Improves missing parameter error messages.

Previously

1. didn't say what type of parameter (header, path, query, body)
2. didn't say name of the missing parameter

- f2240bd clarifies the missing parameter error messages
- c3a993d makes a body field required, so we can see that in our sample

### CODE REVIEW

**Comment by nathanleiby** [comment]
@alsmola I actually don't know, my guess was that a previous commit didn't update the samples after making a change

**Comment by nathanleiby** [comment]
Lemme make sure all my deps are correct locally... maybe it's me 😨

**Comment by nathanleiby** [comment]
Looks like my dependencies were out of date locally. Thanks for the nudge! I've reverted that commit (c3b9740f0787ae4bd8cf1414badb0e613c0f288b). Running another `make generate` locally shows no changes now.

**Comment by alsmola** [comment]
:1:

**Comment by kvigen** [comment]
lgtm too!

**Pull request merged**
