### PR TITLE
generated -> gen-go

### PR DESCRIPTION
**Pull request by rgarcia**
The `generated` package name was still hardcoded in one place--this PR removes that and moves everything into `gen-go`, the new recommendation in the README.

### CODE REVIEW

**Comment by rgarcia** [comment]
@kvigen I'll wait for #34 to merge and re-run codegen to avoid lots of conflicts

**Comment by kvigen** [comment]
good catch, lgtm. will merge in https://github.com/Clever/wag/pull/34 soon

**Comment by bstein-clever** [comment]
Nice, thanks!

**Comment by rgarcia** [comment]
rebased, merging

**Pull request merged**
